"""add client contact

Revision ID: 6b1c9501a045
Revises: 75585c6d0305
Create Date: 2026-08-02 12:07:51.657054

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1c9501a045'
down_revision: Union[str, None] = '75585c6d0305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipment', sa.Column('client_contafct_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contafct_phone')
    op.drop_column('shipment', 'client_contact_email')
    # ### end Alembic commands ###
