"""sync models

Revision ID: 75585c6d0305
Revises: c62583709171
Create Date: 2026-08-01 13:36:41.893478

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75585c6d0305'
down_revision: Union[str, None] = 'c62583709171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partner',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('serviceable_zip_codes', sa.ARRAY(sa.INTEGER()), nullable=True),
    sa.Column('max_handling_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('seller', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('seller', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('seller', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('shipment', sa.Column('destination', sa.Integer(), nullable=False))
    op.add_column('shipment', sa.Column('estimated_delivery', sa.DateTime(), nullable=False))
    op.add_column('shipment', sa.Column('seller_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'shipment', 'delivery_partner', ['delivery_partner_id'], ['id'])
    op.create_foreign_key(None, 'shipment', 'seller', ['seller_id'], ['id'])
    op.alter_column('shipment_event', 'status',
               existing_type=postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment_event', 'status',
               existing_type=postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'),
               nullable=True)
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'seller_id')
    op.drop_column('shipment', 'estimated_delivery')
    op.drop_column('shipment', 'destination')
    op.drop_column('shipment', 'weight')
    op.drop_column('shipment', 'content')
    op.drop_column('shipment', 'created_at')
    op.drop_column('seller', 'password_hash')
    op.drop_column('seller', 'email')
    op.drop_column('seller', 'name')
    op.drop_table('delivery_partner')
    # ### end Alembic commands ###
