"""add user email_verified

Revision ID: baa760a11465
Revises: 6b1c9501a045
Create Date: 2026-08-17 11:09:37.467247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa760a11465'
down_revision = '6b1c9501a045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=True, server_default=sa.false()))

    op.execute("UPDATE delivery_partner SET email_verified = false WHERE email_verified IS NULL")
    op.execute("UPDATE seller SET email_verified = false WHERE email_verified IS NULL")

    op.alter_column('delivery_partner', 'email_verified', nullable=False, server_default=sa.false())
    op.alter_column('seller', 'email_verified', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###